version: '3.8'

services:
 traffic-man:
 # you can remove the dns section if you want the container to use the host dns by default, or you can edit these addresses to suite your needs
  dns: 
    - "192.168.1.2"
    - "8.8.8.8"
  image: coder-sms-register:latest
  # fill in the .env file with your account id, keys, phone numbers, etc
  env_file:
    - .env
  tty: true
  stdin_open: true
  ports:
   - "8000:8000"
  # this is where our log and db file will be
  volumes:
   - etc:/etc/coder-sms-register
   
volumes:
 etc: